# Generated by Django 3.2.9 on 2021-11-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bacia', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('formac', models.TextField()),
            ],
        ),
    ]
