# Generated by Django 3.2.9 on 2021-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='well',
            name='long',
            field=models.FloatField(),
        ),
    ]
