# Generated by Django 3.2.9 on 2021-11-16 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Well',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bacia', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('formac', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
